package com.xgksyjxpt.xgksyjxpt.course.domain.teacher;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.tid
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.tname
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.age
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.sex
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.tid
     *
     * @return the value of teacher_t.tid
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.tid
     *
     * @param tid the value for teacher_t.tid
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.tname
     *
     * @return the value of teacher_t.tname
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.tname
     *
     * @param tname the value for teacher_t.tname
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public void setTname(String tname) {
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.age
     *
     * @return the value of teacher_t.age
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.age
     *
     * @param age the value for teacher_t.age
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.sex
     *
     * @return the value of teacher_t.sex
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.sex
     *
     * @param sex the value for teacher_t.sex
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_t.passwd
     *
     * @return the value of teacher_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_t.passwd
     *
     * @param passwd the value for teacher_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}