package com.xgksyjxpt.xgksyjxpt.course.domain.teacher;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "教师头像类")
public class TeacherHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_head_t.tid
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    @ApiModelProperty(value = "老师id",dataType = "String",required = true)
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_head_t.head_link
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    @ApiModelProperty(value = "老师头像url",dataType = "String",required = true)
    private String headLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_head_t.tid
     *
     * @return the value of teacher_head_t.tid
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_head_t.tid
     *
     * @param tid the value for teacher_head_t.tid
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_head_t.head_link
     *
     * @return the value of teacher_head_t.head_link
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    public String getHead_link() {
        return headLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_head_t.head_link
     *
     * @param head_link the value for teacher_head_t.head_link
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    public void setHead_link(String head_link) {
        this.headLink = head_link;
    }
}