package com.xgksyjxpt.xgksyjxpt.course.domain.student;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_t.stu_id
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    private String stu_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_t.name
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_t.age
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_t.sex
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    private String passwd;
    private String class_name;

    public String getClass_name() {
        return class_name;
    }

    public void setClass_name(String class_name) {
        this.class_name = class_name;
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_t.stu_id
     *
     * @return the value of student_t.stu_id
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public String getStu_id() {
        return stu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_t.stu_id
     *
     * @param stu_id the value for student_t.stu_id
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public void setStu_id(String stu_id) {
        this.stu_id = stu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_t.name
     *
     * @return the value of student_t.name
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_t.name
     *
     * @param name the value for student_t.name
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_t.age
     *
     * @return the value of student_t.age
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_t.age
     *
     * @param age the value for student_t.age
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_t.sex
     *
     * @return the value of student_t.sex
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_t.sex
     *
     * @param sex the value for student_t.sex
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_t.passwd
     *
     * @return the value of student_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_t.passwd
     *
     * @param passwd the value for student_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}