package com.xgksyjxpt.xgksyjxpt.course.domain.student;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "学生选课类")
public class StudentCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.id
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    @ApiModelProperty(value = "id",dataType = "String",hidden = true)
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.stu_id
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    @ApiModelProperty(value = "学生id",dataType = "String",required = true)
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.cid
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    @ApiModelProperty(value = "课程id",dataType = "String",required = true)
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_course.score
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    @ApiModelProperty(value = "成绩",dataType = "String",required = true)
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.id
     *
     * @return the value of student_course.id
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.id
     *
     * @param id the value for student_course.id
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.stu_id
     *
     * @return the value of student_course.stu_id
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.stu_id
     *
     * @param sid the value for student_course.stu_id
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.cid
     *
     * @return the value of student_course.cid
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.cid
     *
     * @param cid the value for student_course.cid
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_course.score
     *
     * @return the value of student_course.score
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_course.score
     *
     * @param score the value for student_course.score
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}