package com.xgksyjxpt.xgksyjxpt.course.domain.student;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "学生头像类")
public class StudentHead {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_head_t.stu_id
     *
     * @mbggenerated Tue Dec 13 21:48:52 CST 2022
     */
    @ApiModelProperty(value = "学生id",dataType = "String",required = true)
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_head_t.head_link
     *
     * @mbggenerated Tue Dec 13 21:48:52 CST 2022
     */
    @ApiModelProperty(value = "学生头像url",dataType = "String",required = true)
    private String head_link;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_head_t.stu_id
     *
     * @return the value of student_head_t.stu_id
     *
     * @mbggenerated Tue Dec 13 21:48:52 CST 2022
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_head_t.stu_id
     *
     * @param sid the value for student_head_t.stu_id
     *
     * @mbggenerated Tue Dec 13 21:48:52 CST 2022
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_head_t.head_link
     *
     * @return the value of student_head_t.head_link
     *
     * @mbggenerated Tue Dec 13 21:48:52 CST 2022
     */
    public String getHead_link() {
        return head_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_head_t.head_link
     *
     * @param head_link the value for student_head_t.head_link
     *
     * @mbggenerated Tue Dec 13 21:48:52 CST 2022
     */
    public void setHead_link(String head_link) {
        this.head_link = head_link;
    }
}