package com.xgksyjxpt.xgksyjxpt.course.domain.student;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "学生实验类")
public class StudentTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_test_t.test_id
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    @ApiModelProperty(value = "实验id",dataType = "String",required = true)
    private String testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_test_t.cid
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    @ApiModelProperty(value = "课程id",dataType = "String",required = true)
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_test_t.stu_id
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    @ApiModelProperty(value = "学生id",dataType = "String",required = true)
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_test_t.score
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    @ApiModelProperty(value = "成绩",dataType = "String",required = true)
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_test_t.test_id
     *
     * @return the value of student_test_t.test_id
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    public String getTest_id() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_test_t.test_id
     *
     * @param test_id the value for student_test_t.test_id
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    public void setTest_id(String test_id) {
        this.testId = test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_test_t.cid
     *
     * @return the value of student_test_t.cid
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_test_t.cid
     *
     * @param cid the value for student_test_t.cid
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_test_t.stu_id
     *
     * @return the value of student_test_t.stu_id
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_test_t.stu_id
     *
     * @param sid the value for student_test_t.stu_id
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_test_t.score
     *
     * @return the value of student_test_t.score
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_test_t.score
     *
     * @param score the value for student_test_t.score
     *
     * @mbggenerated Sat Dec 17 13:46:24 CST 2022
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}