package com.xgksyjxpt.xgksyjxpt.course.mapper.admin;

import com.xgksyjxpt.xgksyjxpt.course.domain.admin.AdminHead;

public interface AdminHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_head_t
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    int insert(AdminHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_head_t
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    int insertSelective(AdminHead record);
    /**
     * 查询管理员头像链接
     */
    String selectAdminHeadUrl(String rid);
    /**
     * 设置管理员头像
     */
    int insertAdminHead(AdminHead adminHead);

    /**
     * 修改管理员头像
     * @param adminHead
     * @return
     */
    int updateAdminHead(AdminHead adminHead);
    /**
     * 删除管理员头像
     */
    int deleteAdminHead(String rid);
}