package com.xgksyjxpt.xgksyjxpt.course.mapper.admin;

import com.xgksyjxpt.xgksyjxpt.course.domain.admin.Admin;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int deleteByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    Admin selectByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int updateByPrimaryKey(Admin record);

    Admin selectAdmin(String id);

}