package com.xgksyjxpt.xgksyjxpt.course.mapper.admin;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.xgksyjxpt.xgksyjxpt.course.domain.admin.Admin;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdminMapper extends BaseMapper<Admin> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int deleteByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    Admin selectByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int updateByPrimaryKey(Admin record);

    /**
     * 根据管理员id查询正常状态的管理员账号信息
     * @param id
     * @return
     */
    Admin selectNotDelAdmin(String id);

    /**
     * 添加管理员
     */
    int insertAdmin(Admin admin);
    /**
     * 修改管理员信息
     */
    int updateAdmin(Admin admin);
    /**
     * 修改管理员密码
     */
    int updateAdminPass(@Param("rid") String rid,@Param("pass") String pass);
    /**
     * 批量删除管理员
     */
    int deleteAdmins(String[] rids);
    /**
     * 根据管理员id查询管理员账号信息
     */
    Admin selectAdmin(String rid);
    /**
     * 查询所有普通管理员账号信息
     */
    List<Admin> selectCommonAdmin(@Param("admin") Admin admin,@Param("pageNum") Integer pageNum,@Param("pageSize") Integer pageSize);
    /**
     * 查询普通管理员账号总数
     */
    int queryAdminCount(Admin admin);
    /**
     * 查询普通管理员的id
     */
    List<String> selectAdminRid();
}