package com.xgksyjxpt.xgksyjxpt.course.mapper.admin;

import com.xgksyjxpt.xgksyjxpt.course.domain.admin.Admin;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int deleteByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    Admin selectByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_t
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    int updateByPrimaryKey(Admin record);

    /**
     * 查询正常状态的管理员账号
     * @param id
     * @return
     */
    Admin selectNotDelAdmin(String id);

    /**
     * 添加管理员
     */
    int insertAdmin(Admin admin);
    /**
     * 修改管理员信息
     */
    int updateAdmin(Admin admin);
    /**
     * 修改管理员密码
     */
    int updateAdminPass(@Param("rid") String rid,@Param("pass") String pass);
    /**
     * 删除管理员
     */
    int deleteAdmin(String rid);
    /**
     * 查询所有管理员账号
     */
    Admin selectAdmin(String rid);
}