package com.xgksyjxpt.xgksyjxpt.course.mapper.admin;

import com.xgksyjxpt.xgksyjxpt.course.domain.admin.IdentityPermissions;

import java.util.List;

public interface IdentityPermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_permissions_t
     *
     * @mbggenerated Sat Feb 11 20:34:05 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_permissions_t
     *
     * @mbggenerated Sat Feb 11 20:34:05 CST 2023
     */
    int insert(IdentityPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_permissions_t
     *
     * @mbggenerated Sat Feb 11 20:34:05 CST 2023
     */
    int insertSelective(IdentityPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_permissions_t
     *
     * @mbggenerated Sat Feb 11 20:34:05 CST 2023
     */
    IdentityPermissions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_permissions_t
     *
     * @mbggenerated Sat Feb 11 20:34:05 CST 2023
     */
    int updateByPrimaryKeySelective(IdentityPermissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_permissions_t
     *
     * @mbggenerated Sat Feb 11 20:34:05 CST 2023
     */
    int updateByPrimaryKey(IdentityPermissions record);
    /**
     * 查询指定角色权限
     */
    List<String> selectIdentityPermissions(String identity);
    /**
     * 给指定角色添加权限
     */
    int insertIdentityPermissions(IdentityPermissions identityPermissions);
    /**
     * 删除角色权限
     */
    int deleteIdentityPermissions(IdentityPermissions identityPermissions);
}