package com.xgksyjxpt.xgksyjxpt.course.mapper.admin;

import com.xgksyjxpt.xgksyjxpt.course.domain.admin.Identity;

import java.util.List;

public interface IdentityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_t
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_t
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    int insert(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_t
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    int insertSelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_t
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    Identity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_t
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    int updateByPrimaryKeySelective(Identity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table identity_t
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    int updateByPrimaryKey(Identity record);
//    查询所有角色
    List<String> selectAllIdentity();
    /**
     * 添加角色
     */
    int insertIdentity(String identity);
    /**
     * 删除角色
     */
    int deleteIdentity(String identity);
}