package com.xgksyjxpt.xgksyjxpt.course.domain.course;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

/**
 * @Builder @Data 使用该注解后无参构造丢失
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ApiModel(value = "运行容器类")
public class Container {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runcontainer.id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    @ApiModelProperty(value = "id",dataType = "String",hidden = false)
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runcontainer.stu_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    @ApiModelProperty(value = "学生id",dataType = "String",required = true)
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runcontainer.test_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    @ApiModelProperty(value = "实验id",dataType = "String",required = true)
    private String testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runcontainer.container_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    @ApiModelProperty(value = "容器id",dataType = "String",required = true)
    private String containerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runcontainer.container_startTime
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    @ApiModelProperty(value = "容器运行时间",dataType = "String",required = true)
    private Date containerStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runcontainer.container_endTime
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    @ApiModelProperty(value = "容器结束时间",dataType = "String")
    private Date containerEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column runcontainer.passwd
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    @ApiModelProperty(value = "容器ssh密码",dataType = "String",required = true)
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runcontainer.id
     *
     * @return the value of runcontainer.id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runcontainer.id
     *
     * @param id the value for runcontainer.id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runcontainer.stu_id
     *
     * @return the value of runcontainer.stu_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runcontainer.stu_id
     *
     * @param sid the value for runcontainer.stu_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runcontainer.test_id
     *
     * @return the value of runcontainer.test_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public String getTest_id() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runcontainer.test_id
     *
     * @param testId the value for runcontainer.test_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setTest_id(String testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runcontainer.container_id
     *
     * @return the value of runcontainer.container_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public String getContainer_id() {
        return containerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runcontainer.container_id
     *
     * @param containerId the value for runcontainer.container_id
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setContainer_id(String containerId) {
        this.containerId = containerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runcontainer.container_startTime
     *
     * @return the value of runcontainer.container_startTime
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public Date getContainer_startTime() {
        return containerStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runcontainer.container_startTime
     *
     * @param container_startTime the value for runcontainer.container_startTime
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setContainer_startTime(Date container_startTime) {
        this.containerStartTime = container_startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runcontainer.container_endTime
     *
     * @return the value of runcontainer.container_endTime
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public Date getContainer_endTime() {
        return containerEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runcontainer.container_endTime
     *
     * @param container_endTime the value for runcontainer.container_endTime
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setContainer_endTime(Date container_endTime) {
        this.containerEndTime = container_endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column runcontainer.passwd
     *
     * @return the value of runcontainer.passwd
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column runcontainer.passwd
     *
     * @param passwd the value for runcontainer.passwd
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}