package com.xgksyjxpt.xgksyjxpt.course.domain.course;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "课程小节类")
public class CourseSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.section_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "小节id",dataType = "int",required = false)
    private Integer section_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.section_name
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "小节标题",dataType = "String",required = true)
    private String section_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.cid
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "课程id",dataType = "String",required = true)
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "章节id",dataType = "int",required = true)
    private Integer chapter_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.section_text
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "小节内容",dataType = "String",required = true)
    private String section_text;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.section_id
     *
     * @return the value of course_section_t.section_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public Integer getSection_id() {
        return section_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.section_id
     *
     * @param section_id the value for course_section_t.section_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setSection_id(Integer section_id) {
        this.section_id = section_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.section_name
     *
     * @return the value of course_section_t.section_name
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public String getSection_name() {
        return section_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.section_name
     *
     * @param section_name the value for course_section_t.section_name
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setSection_name(String section_name) {
        this.section_name = section_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.cid
     *
     * @return the value of course_section_t.cid
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.cid
     *
     * @param cid the value for course_section_t.cid
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.chapter_id
     *
     * @return the value of course_section_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public Integer getChapter_id() {
        return chapter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.chapter_id
     *
     * @param chapter_id the value for course_section_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setChapter_id(Integer chapter_id) {
        this.chapter_id = chapter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.section_text
     *
     * @return the value of course_section_t.section_text
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public String getSection_text() {
        return section_text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.section_text
     *
     * @param section_text the value for course_section_t.section_text
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setSection_text(String section_text) {
        this.section_text = section_text;
    }
}