package com.xgksyjxpt.xgksyjxpt.course.domain.course;

public class CourseChapterKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_chapter_t.cid
     *
     * @mbggenerated Sun Dec 18 15:21:05 CST 2022
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_chapter_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:21:05 CST 2022
     */
    private Integer chapter_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_chapter_t.cid
     *
     * @return the value of course_chapter_t.cid
     *
     * @mbggenerated Sun Dec 18 15:21:05 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_chapter_t.cid
     *
     * @param cid the value for course_chapter_t.cid
     *
     * @mbggenerated Sun Dec 18 15:21:05 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_chapter_t.chapter_id
     *
     * @return the value of course_chapter_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:21:05 CST 2022
     */
    public Integer getChapter_id() {
        return chapter_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_chapter_t.chapter_id
     *
     * @param chapter_id the value for course_chapter_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:21:05 CST 2022
     */
    public void setChapter_id(Integer chapter_id) {
        this.chapter_id = chapter_id;
    }
}