package com.xgksyjxpt.xgksyjxpt.course.domain.course;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
@ApiModel(value = "课程实验类")
public class CourseTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_t.test_id
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    @ApiModelProperty(value = "实验id",dataType = "String",required = true)
    private String testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_t.cid
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    @ApiModelProperty(value = "课程id",dataType = "String",required = true)
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_t.test_name
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    @ApiModelProperty(value = "实验名称",dataType = "String",required = true)
    private String testName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_t.test_image_name
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    @ApiModelProperty(value = "实验镜像名",dataType = "String",required = true)
    private String testImageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_t.test_start_time
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    @ApiModelProperty(value = "实验开始时间",dataType = "String",required = true)
    private String testStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_t.test_end_time
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    @ApiModelProperty(value = "实验结束时间",dataType = "String",required = true)
    private String testEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_t.test_description
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    @ApiModelProperty(value = "实验描述",dataType = "String",required = true)
    private String testDescription;
    @ApiModelProperty(value = "实验状态",dataType = "String",required = true,example = "已开始/未开始/已结束")
    private String testStatus;
    @ApiModelProperty(value = "实验状态",dataType = "String",required = true,example = "已开始/未开始/已结束")
    private Integer chapterId;

    public Integer getChapterId() {
        return chapterId;
    }

    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }

    public String getTest_status() {
        return testStatus;
    }

    public void setTest_status(String test_status) {
        this.testStatus = test_status;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_test_t.test_id
     *
     * @return the value of course_test_t.test_id
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public String getTest_id() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_test_t.test_id
     *
     * @param test_id the value for course_test_t.test_id
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public void setTest_id(String test_id) {
        this.testId = test_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_test_t.cid
     *
     * @return the value of course_test_t.cid
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_test_t.cid
     *
     * @param cid the value for course_test_t.cid
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_test_t.test_name
     *
     * @return the value of course_test_t.test_name
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public String getTest_name() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_test_t.test_name
     *
     * @param test_name the value for course_test_t.test_name
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public void setTest_name(String test_name) {
        this.testName = test_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_test_t.test_image_name
     *
     * @return the value of course_test_t.test_image_name
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public String getTest_image_name() {
        return testImageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_test_t.test_image_name
     *
     * @param testImageName the value for course_test_t.test_image_name
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public void setTest_image_name(String testImageName) {
        this.testImageName = testImageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_test_t.test_start_time
     *
     * @return the value of course_test_t.test_start_time
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public String getTest_start_time() {
        return testStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_test_t.test_start_time
     *
     * @param test_start_time the value for course_test_t.test_start_time
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public void setTest_start_time(String test_start_time) {
        this.testStartTime = test_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_test_t.test_end_time
     *
     * @return the value of course_test_t.test_end_time
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public String getTest_end_time() {
        return testEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_test_t.test_end_time
     *
     * @param test_end_time the value for course_test_t.test_end_time
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public void setTest_end_time(String test_end_time) {
        this.testEndTime = test_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_test_t.test_description
     *
     * @return the value of course_test_t.test_description
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public String getTest_description() {
        return testDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_test_t.test_description
     *
     * @param test_description the value for course_test_t.test_description
     *
     * @mbggenerated Sun Dec 18 16:38:23 CST 2022
     */
    public void setTest_description(String test_description) {
        this.testDescription = test_description;
    }
}