package com.xgksyjxpt.xgksyjxpt.course.domain.course;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "课程类")
public class Course {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_t.cid
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */

    @ApiModelProperty(value = "课程id" ,dataType = "String",required = true)
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_t.cname
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    @ApiModelProperty(value = "课程名称",dataType = "String",required = true)
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_t.course_start
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    @ApiModelProperty(value = "课程开始时间",dataType = "String",required = true)
    private String courseStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_t.course_end
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    @ApiModelProperty(value = "课程结束时间",dataType = "String",required = true)
    private String courseEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_t.xuefen
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    @ApiModelProperty(value = "课程学分",dataType = "String",required = false)
    private Integer xuefen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_t.miaoshu
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    @ApiModelProperty(value = "课程描述",dataType = "String")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_t.tid
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    @ApiModelProperty(value = "课程所属老师id",dataType = "String",required = true)
    private String tid;
    @ApiModelProperty(value = "课程状态",dataType = "String",required = true,example = "已开始/已结束/未开始")
    private String courseStatus;


    public String getCourse_status() {
        return courseStatus;
    }

    public void setCourse_status(String courseStatus) {
        this.courseStatus = courseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_t.cid
     *
     * @return the value of course_t.cid
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_t.cid
     *
     * @param cid the value for course_t.cid
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_t.cname
     *
     * @return the value of course_t.cname
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_t.cname
     *
     * @param cname the value for course_t.cname
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_t.course_start
     *
     * @return the value of course_t.course_start
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public String getCourseStart() {
        return courseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_t.course_start
     *
     * @param courseStart the value for course_t.course_start
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public void setCourseStart(String courseStart) {
        this.courseStart = courseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_t.course_end
     *
     * @return the value of course_t.course_end
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public String getCourseEnd() {
        return courseEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_t.course_end
     *
     * @param courseEnd the value for course_t.course_end
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public void setCourseEnd(String courseEnd) {
        this.courseEnd = courseEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_t.xuefen
     *
     * @return the value of course_t.xuefen
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public Integer getXuefen() {
        return xuefen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_t.xuefen
     *
     * @param xuefen the value for course_t.xuefen
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public void setXuefen(Integer xuefen) {
        this.xuefen = xuefen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_t.miaoshu
     *
     * @return the value of course_t.miaoshu
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_t.miaoshu
     *
     * @param description the value for course_t.miaoshu
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_t.tid
     *
     * @return the value of course_t.tid
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_t.tid
     *
     * @param tid the value for course_t.tid
     *
     * @mbggenerated Sat Dec 17 21:33:47 CST 2022
     */
    public void setTid(String tid) {
        this.tid = tid;
    }
}