package com.xgksyjxpt.xgksyjxpt.course.domain.course;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Builder;
import lombok.Data;

@ApiModel(value = "课程封面类")
public class CourseHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_head_t.cid
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    @ApiModelProperty(value = "课程id",dataType = "String",required = true)
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_head_t.course_link
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    @ApiModelProperty(value = "课程封面url",dataType = "String",required = true)
    private String courseLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_head_t.cid
     *
     * @return the value of course_head_t.cid
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_head_t.cid
     *
     * @param cid the value for course_head_t.cid
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_head_t.course_link
     *
     * @return the value of course_head_t.course_link
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    public String getCourse_link() {
        return courseLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_head_t.course_link
     *
     * @param course_link the value for course_head_t.course_link
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    public void setCourse_link(String course_link) {
        this.courseLink = course_link;
    }
}