package com.xgksyjxpt.xgksyjxpt.course.domain.course;

import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

@ApiModel(value = "课程小节类")
@TableName("course_section_t")
public class CourseSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.section_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "小节id",dataType = "int",required = false)
    private Integer sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.section_name
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "小节标题",dataType = "String",required = true)
    private String sectionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.cid
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "课程id",dataType = "String",required = true)
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "章节id",dataType = "int",required = true)
    private Integer chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section_t.section_text
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    @ApiModelProperty(value = "小节内容",dataType = "String",required = true)
    private String sectionText;

    @TableLogic(value = "null",delval = "now()")
    @ApiModelProperty(hidden = true)
    private Date delete_time;

    public Date getDelete_time() {
        return delete_time;
    }

    public void setDelete_time(Date delete_time) {
        this.delete_time = delete_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.section_id
     *
     * @return the value of course_section_t.section_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public Integer getSection_id() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.section_id
     *
     * @param sectionId the value for course_section_t.section_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setSection_id(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.section_name
     *
     * @return the value of course_section_t.section_name
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public String getSection_name() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.section_name
     *
     * @param sectionName the value for course_section_t.section_name
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setSection_name(String sectionName) {
        this.sectionName = sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.cid
     *
     * @return the value of course_section_t.cid
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.cid
     *
     * @param cid the value for course_section_t.cid
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.chapter_id
     *
     * @return the value of course_section_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public Integer getChapter_id() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.chapter_id
     *
     * @param chapterId the value for course_section_t.chapter_id
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setChapter_id(Integer chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section_t.section_text
     *
     * @return the value of course_section_t.section_text
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public String getSection_text() {
        return sectionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section_t.section_text
     *
     * @param sectionText the value for course_section_t.section_text
     *
     * @mbggenerated Sun Dec 18 15:29:39 CST 2022
     */
    public void setSection_text(String sectionText) {
        this.sectionText = sectionText;
    }
}