package com.xgksyjxpt.xgksyjxpt.course.domain.course;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
@ApiModel(value = "课程实验镜像类")
public class CourseTestImages {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_images.images_name
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    @ApiModelProperty(value = "实验可用镜像名",dataType = "String",required = true)
    private String imagesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_test_images.delete_time
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    @ApiModelProperty(value = "添加时间",dataType = "String",required = true)
    private String addTime;

    public String getAdd_time() {
        return addTime;
    }

    public void setAdd_time(String addTime) {
        this.addTime = addTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_test_images.images_name
     *
     * @return the value of course_test_images.images_name
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    public String getImages_name() {
        return imagesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_test_images.images_name
     *
     * @param imagesName the value for course_test_images.images_name
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    public void setImages_name(String imagesName) {
        this.imagesName = imagesName;
    }


}