// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sshService.proto

package com.xgksyjxpt.xgksyjxpt.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string jwtText = 1;</code>
   */
  String getJwtText();
  /**
   * <code>string jwtText = 1;</code>
   */
  com.google.protobuf.ByteString
      getJwtTextBytes();
}
