// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sshService.proto

package com.xgksyjxpt.xgksyjxpt.proto;

public interface SendIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SendId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
