// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sshService.proto

package com.xgksyjxpt.xgksyjxpt.proto;

public interface SshInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SshInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string password = 2;</code>
   */
  String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
