// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sshService.proto

package com.xgksyjxpt.xgksyjxpt.proto;

public final class SshService {
  private SshService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SendId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SendId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_SshInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_SshInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020sshService.proto\022\005proto\"\024\n\006SendId\022\n\n\002i" +
      "d\030\001 \001(\t\"\'\n\007SshInfo\022\n\n\002ip\030\001 \001(\t\022\020\n\010passwo" +
      "rd\030\002 \001(\t\"\032\n\007Request\022\017\n\007jwtText\030\001 \001(\t\"\032\n\010" +
      "Response\022\016\n\006result\030\001 \001(\00529\n\nConService\022+" +
      "\n\nGetSshInfo\022\r.proto.SendId\032\016.proto.SshI" +
      "nfo2:\n\nVerifyAuth\022,\n\tauthToken\022\016.proto.R" +
      "equest\032\017.proto.ResponseB2\n\035com.xgksyjxpt" +
      ".xgksyjxpt.protoP\001Z\017go-webssh/protob\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_SendId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_SendId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SendId_descriptor,
        new String[] { "Id", });
    internal_static_proto_SshInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_SshInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_SshInfo_descriptor,
        new String[] { "Ip", "Password", });
    internal_static_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Request_descriptor,
        new String[] { "JwtText", });
    internal_static_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Response_descriptor,
        new String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
