package com.xgksyjxpt.xgksyjxpt.course.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContainerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public ContainerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStu_idIsNull() {
            addCriterion("stu_id is null");
            return (Criteria) this;
        }

        public Criteria andStu_idIsNotNull() {
            addCriterion("stu_id is not null");
            return (Criteria) this;
        }

        public Criteria andStu_idEqualTo(String value) {
            addCriterion("stu_id =", value, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idNotEqualTo(String value) {
            addCriterion("stu_id <>", value, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idGreaterThan(String value) {
            addCriterion("stu_id >", value, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idGreaterThanOrEqualTo(String value) {
            addCriterion("stu_id >=", value, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idLessThan(String value) {
            addCriterion("stu_id <", value, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idLessThanOrEqualTo(String value) {
            addCriterion("stu_id <=", value, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idLike(String value) {
            addCriterion("stu_id like", value, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idNotLike(String value) {
            addCriterion("stu_id not like", value, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idIn(List<String> values) {
            addCriterion("stu_id in", values, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idNotIn(List<String> values) {
            addCriterion("stu_id not in", values, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idBetween(String value1, String value2) {
            addCriterion("stu_id between", value1, value2, "stu_id");
            return (Criteria) this;
        }

        public Criteria andStu_idNotBetween(String value1, String value2) {
            addCriterion("stu_id not between", value1, value2, "stu_id");
            return (Criteria) this;
        }

        public Criteria andTest_idIsNull() {
            addCriterion("test_id is null");
            return (Criteria) this;
        }

        public Criteria andTest_idIsNotNull() {
            addCriterion("test_id is not null");
            return (Criteria) this;
        }

        public Criteria andTest_idEqualTo(String value) {
            addCriterion("test_id =", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotEqualTo(String value) {
            addCriterion("test_id <>", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idGreaterThan(String value) {
            addCriterion("test_id >", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idGreaterThanOrEqualTo(String value) {
            addCriterion("test_id >=", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idLessThan(String value) {
            addCriterion("test_id <", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idLessThanOrEqualTo(String value) {
            addCriterion("test_id <=", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idLike(String value) {
            addCriterion("test_id like", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotLike(String value) {
            addCriterion("test_id not like", value, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idIn(List<String> values) {
            addCriterion("test_id in", values, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotIn(List<String> values) {
            addCriterion("test_id not in", values, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idBetween(String value1, String value2) {
            addCriterion("test_id between", value1, value2, "test_id");
            return (Criteria) this;
        }

        public Criteria andTest_idNotBetween(String value1, String value2) {
            addCriterion("test_id not between", value1, value2, "test_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idIsNull() {
            addCriterion("container_id is null");
            return (Criteria) this;
        }

        public Criteria andContainer_idIsNotNull() {
            addCriterion("container_id is not null");
            return (Criteria) this;
        }

        public Criteria andContainer_idEqualTo(String value) {
            addCriterion("container_id =", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idNotEqualTo(String value) {
            addCriterion("container_id <>", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idGreaterThan(String value) {
            addCriterion("container_id >", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idGreaterThanOrEqualTo(String value) {
            addCriterion("container_id >=", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idLessThan(String value) {
            addCriterion("container_id <", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idLessThanOrEqualTo(String value) {
            addCriterion("container_id <=", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idLike(String value) {
            addCriterion("container_id like", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idNotLike(String value) {
            addCriterion("container_id not like", value, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idIn(List<String> values) {
            addCriterion("container_id in", values, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idNotIn(List<String> values) {
            addCriterion("container_id not in", values, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idBetween(String value1, String value2) {
            addCriterion("container_id between", value1, value2, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_idNotBetween(String value1, String value2) {
            addCriterion("container_id not between", value1, value2, "container_id");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeIsNull() {
            addCriterion("container_startTime is null");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeIsNotNull() {
            addCriterion("container_startTime is not null");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeEqualTo(Date value) {
            addCriterion("container_startTime =", value, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeNotEqualTo(Date value) {
            addCriterion("container_startTime <>", value, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeGreaterThan(Date value) {
            addCriterion("container_startTime >", value, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("container_startTime >=", value, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeLessThan(Date value) {
            addCriterion("container_startTime <", value, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeLessThanOrEqualTo(Date value) {
            addCriterion("container_startTime <=", value, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeIn(List<Date> values) {
            addCriterion("container_startTime in", values, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeNotIn(List<Date> values) {
            addCriterion("container_startTime not in", values, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeBetween(Date value1, Date value2) {
            addCriterion("container_startTime between", value1, value2, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_startTimeNotBetween(Date value1, Date value2) {
            addCriterion("container_startTime not between", value1, value2, "container_startTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeIsNull() {
            addCriterion("container_endTime is null");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeIsNotNull() {
            addCriterion("container_endTime is not null");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeEqualTo(Date value) {
            addCriterion("container_endTime =", value, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeNotEqualTo(Date value) {
            addCriterion("container_endTime <>", value, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeGreaterThan(Date value) {
            addCriterion("container_endTime >", value, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("container_endTime >=", value, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeLessThan(Date value) {
            addCriterion("container_endTime <", value, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeLessThanOrEqualTo(Date value) {
            addCriterion("container_endTime <=", value, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeIn(List<Date> values) {
            addCriterion("container_endTime in", values, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeNotIn(List<Date> values) {
            addCriterion("container_endTime not in", values, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeBetween(Date value1, Date value2) {
            addCriterion("container_endTime between", value1, value2, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andContainer_endTimeNotBetween(Date value1, Date value2) {
            addCriterion("container_endTime not between", value1, value2, "container_endTime");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNull() {
            addCriterion("passwd is null");
            return (Criteria) this;
        }

        public Criteria andPasswdIsNotNull() {
            addCriterion("passwd is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEqualTo(String value) {
            addCriterion("passwd =", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotEqualTo(String value) {
            addCriterion("passwd <>", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThan(String value) {
            addCriterion("passwd >", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("passwd >=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThan(String value) {
            addCriterion("passwd <", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLessThanOrEqualTo(String value) {
            addCriterion("passwd <=", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdLike(String value) {
            addCriterion("passwd like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotLike(String value) {
            addCriterion("passwd not like", value, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdIn(List<String> values) {
            addCriterion("passwd in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotIn(List<String> values) {
            addCriterion("passwd not in", values, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdBetween(String value1, String value2) {
            addCriterion("passwd between", value1, value2, "passwd");
            return (Criteria) this;
        }

        public Criteria andPasswdNotBetween(String value1, String value2) {
            addCriterion("passwd not between", value1, value2, "passwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table runcontainer
     *
     * @mbggenerated do_not_delete_during_merge Sat Nov 26 23:51:19 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}