package com.xgksyjxpt.xgksyjxpt.course.mapper;

import com.xgksyjxpt.xgksyjxpt.course.domain.Container;
import com.xgksyjxpt.xgksyjxpt.course.domain.ContainerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContainerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int countByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int deleteByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int insert(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int insertSelective(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    List<Container> selectByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    Container selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int updateByExampleSelective(@Param("record") Container record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int updateByExample(@Param("record") Container record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int updateByPrimaryKeySelective(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int updateByPrimaryKey(Container record);

    int createContainer(Container container);

    String queryPasswd(String cid);
}