package com.xgksyjxpt.xgksyjxpt.course.mapper;

import com.xgksyjxpt.xgksyjxpt.course.domain.Student;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int deleteByPrimaryKey(String stu_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    Student selectByPrimaryKey(String stu_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int updateByPrimaryKey(Student record);

    Student selectStudent(String id);

    List<Student> queryAllStudent();

    int updateStudent(Student student);

    int insertStudent(Student[] students);

    int insertStudentOne(Student student);
}