package com.xgksyjxpt.xgksyjxpt.course.mapper;

import com.xgksyjxpt.xgksyjxpt.course.domain.Student;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int deleteByPrimaryKey(String stu_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    Student selectByPrimaryKey(String stu_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_t
     *
     * @mbggenerated Sun Nov 27 14:20:38 CST 2022
     */
    int updateByPrimaryKey(Student record);

    /**
     * 查询单个学生信息
     * @param id
     * @return
     */
    Student selectStudent(String id);

    /**
     * 查询所有学生
     * @return
     */
    List<Student> queryAllStudent();

    /**
     * 修改学生基本信息(不包括密码)
     * @param student
     * @return
     */
    int updateStudent(Student student);

    /**
     * 批量添加学生
     * @param students
     * @return
     */
    int insertStudent(Student[] students);

    /**
     * 添加单个学生
     * @param student
     * @return
     */
    int insertStudentOne(Student student);
    /**
     * 修改学生密码
     */
    int updateStuPass(@Param("stu_id")String sid, @Param("passwd")String passwd);

    /**
     * 查询学生密码
     */
    String selectStuPass(String stu_id);
}