package com.xgksyjxpt.xgksyjxpt.course.mapper.teacher;

import com.xgksyjxpt.xgksyjxpt.course.domain.teacher.TeacherHead;

public interface TeacherHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_head_t
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    int deleteByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_head_t
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    int insert(TeacherHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_head_t
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    int insertSelective(TeacherHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_head_t
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    TeacherHead selectByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_head_t
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    int updateByPrimaryKeySelective(TeacherHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_head_t
     *
     * @mbggenerated Fri Dec 16 14:52:20 CST 2022
     */
    int updateByPrimaryKey(TeacherHead record);

    int uploadTeaHead(TeacherHead teacherHead);
    /**
     * 查询老师头像url
     */
    String selectTeaHeadUrlByTid(String tid);
    /**
     * 删除老师头像记录
     */
    int deleteTeaHeadByTid(String tid);
    /**
     * 批量删除老师头像记录
     */
    int deleteTeaHeadByTids(String[] tids);

}