package com.xgksyjxpt.xgksyjxpt.course.domain.admin;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description  = "管理员类")
public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_t.rid
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    @ApiModelProperty(value = "管理员id",dataType = "String",required = true)
    private String rid;


    @ApiModelProperty(value = "管理员名称",dataType = "String",required = true)
    private String name;

    @ApiModelProperty(value = "身份",dataType = "String",required = true)
    private String identity;

    public String getIdentity() {
        return identity;
    }

    public void setIdentity(String identity) {
        this.identity = identity;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    @ApiModelProperty(value = "密码",dataType = "String",required = true)
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_t.rid
     *
     * @return the value of admin_t.rid
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_t.rid
     *
     * @param rid the value for admin_t.rid
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_t.passwd
     *
     * @return the value of admin_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_t.passwd
     *
     * @param passwd the value for admin_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}