package com.xgksyjxpt.xgksyjxpt.course.domain.admin;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_t.rid
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    private String rid;



    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_t.rid
     *
     * @return the value of admin_t.rid
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_t.rid
     *
     * @param rid the value for admin_t.rid
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_t.passwd
     *
     * @return the value of admin_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_t.passwd
     *
     * @param passwd the value for admin_t.passwd
     *
     * @mbggenerated Sun Nov 27 14:20:19 CST 2022
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
}