package com.xgksyjxpt.xgksyjxpt.course.domain.admin;

import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;
@ApiModel(description  = "管理员头像类")
@TableName("admin_head_t")
public class AdminHead {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_head_t.rid
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    @ApiModelProperty(value = "管理员id",dataType = "String",required = true)
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_head_t.head_link
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    @ApiModelProperty(value = "管理员头像url",dataType = "String",required = true)
    private String head_link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_head_t.delete_time
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    @TableLogic(value = "null",delval = "now()")
    private Date delete_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_head_t.rid
     *
     * @return the value of admin_head_t.rid
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_head_t.rid
     *
     * @param rid the value for admin_head_t.rid
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_head_t.head_link
     *
     * @return the value of admin_head_t.head_link
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    public String getHead_link() {
        return head_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_head_t.head_link
     *
     * @param head_link the value for admin_head_t.head_link
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    public void setHead_link(String head_link) {
        this.head_link = head_link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_head_t.delete_time
     *
     * @return the value of admin_head_t.delete_time
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    public Date getDelete_time() {
        return delete_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_head_t.delete_time
     *
     * @param delete_time the value for admin_head_t.delete_time
     *
     * @mbggenerated Sun Jan 01 17:06:12 CST 2023
     */
    public void setDelete_time(Date delete_time) {
        this.delete_time = delete_time;
    }
}