package com.xgksyjxpt.xgksyjxpt.course.domain.admin;

import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;

import java.util.Date;
@TableName("identity_t")
public class Identity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity_t.id
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column identity_t.identity
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    private String identity;

    @TableLogic(value = "null",delval = "now()")
    private Date delete_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity_t.id
     *
     * @return the value of identity_t.id
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity_t.id
     *
     * @param id the value for identity_t.id
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column identity_t.identity
     *
     * @return the value of identity_t.identity
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column identity_t.identity
     *
     * @param identity the value for identity_t.identity
     *
     * @mbggenerated Sat Feb 11 20:34:35 CST 2023
     */
    public void setIdentity(String identity) {
        this.identity = identity;
    }
}