package com.xgksyjxpt.xgksyjxpt.login.mapper;

import com.xgksyjxpt.xgksyjxpt.login.domain.Teacher;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    int deleteByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    Teacher selectByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_t
     *
     * @mbggenerated Sun Nov 27 14:17:20 CST 2022
     */
    int updateByPrimaryKey(Teacher record);

    Teacher selectTeacher(String id);
}