package com.xgksyjxpt.xgksyjxpt.course.mapper.student;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.xgksyjxpt.xgksyjxpt.course.domain.student.StudentCourse;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface StudentCourseMapper extends BaseMapper<StudentCourse> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    int insert(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    int insertSelective(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    StudentCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    int updateByPrimaryKeySelective(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_course
     *
     * @mbggenerated Sat Dec 17 13:45:48 CST 2022
     */
    int updateByPrimaryKey(StudentCourse record);
    /**
     * 批量删除学生选课记录
     */
    int deleteStuCourse(String[] stuIds);
    /**
     * 根据课程号删除学生选课记录
     */
    int deleteStuCourseByCid(String cid);
    /**
     * 根据课程号查询选课人数
     */
    int queryStuCourseCourseByCid(String cid);
    /**
     * 根据课程号添加学生选课记录
     */
    int insertStudentCourseByCid(@Param("stuIds") String[] stuIds, @Param("cid") String cid);
    /**
     * 根据课程号查询选课学生学号
     */
    List<String> selectStudentCourseSidByCId(String cid);
    /**
     * 根据课程号查询选课班级
     */
    List<String> selectStudentCourseClassNameByCid(String cid);
    /**
     * 查询指定学号选课信息
     */
    List<Map<String,Object>> selectStudentCourseInfoBySId(@Param("sid")String sid,@Param("pageNum")Integer pageNum,@Param("pageSize")Integer pageSize);
}