package com.xgksyjxpt.xgksyjxpt.course.mapper.course;

import com.xgksyjxpt.xgksyjxpt.course.domain.course.Container;
import com.xgksyjxpt.xgksyjxpt.course.domain.course.ContainerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContainerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int countByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int deleteByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int insert(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int insertSelective(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    List<Container> selectByExample(ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    Container selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int updateByExampleSelective(@Param("record") Container record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int updateByExample(@Param("record") Container record, @Param("example") ContainerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int updateByPrimaryKeySelective(Container record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table runcontainer
     *
     * @mbggenerated Sat Nov 26 23:51:19 CST 2022
     */
    int updateByPrimaryKey(Container record);

    /**
     * 添加运行记录
     * @param container
     * @return
     */
    int createContainer(Container container);

    /**
     * 查询容器密码
     * @param cid
     * @return
     */
    String queryPasswd(String cid);

    /**
     * 根据学号删除运行记录
     * @param stuIds
     * @return
     */
    int deleteStuContainer(String[] stuIds);

    /**
     * 查询学生使用的容器名
     */
    List<String> selectStuContainerId(String stuId);
    /**
     * 根据实验id删除实验记录
     */
    int deleteContainerByTestId(String testId);
    /**
     * 根据实验id查询容器id
     */
    List<String> selectContainerIdByTestId(String testId);

}