package com.xgksyjxpt.xgksyjxpt.course.mapper.course;

import com.xgksyjxpt.xgksyjxpt.course.domain.course.CourseHead;

public interface CourseHeadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_head_t
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_head_t
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    int insert(CourseHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_head_t
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    int insertSelective(CourseHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_head_t
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    CourseHead selectByPrimaryKey(String cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_head_t
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    int updateByPrimaryKeySelective(CourseHead record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_head_t
     *
     * @mbggenerated Sat Dec 17 21:54:18 CST 2022
     */
    int updateByPrimaryKey(CourseHead record);
    /**
     * 添加课程封面记录
     */
    int insertCourseHead(CourseHead courseHead);
    /**
     * 根据课程号删除课程封面记录
     */
    int deleteCourseHeadByCid(String cid);
    /**
     * 根据课程号查询封面url
     */
    String selectCourseHeadUrlByCid(String cid);

    /**
     * 修改课程封面
     */
    int updateCourseHead(CourseHead courseHead);
}