package com.xgksyjxpt.xgksyjxpt.course.mapper.course;

import com.xgksyjxpt.xgksyjxpt.course.domain.course.CourseTestImages;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CourseTestImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test_images
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test_images
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    int insert(CourseTestImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test_images
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    int insertSelective(CourseTestImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test_images
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    CourseTestImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test_images
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    int updateByPrimaryKeySelective(CourseTestImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_test_images
     *
     * @mbggenerated Wed Dec 28 20:41:03 CST 2022
     */
    int updateByPrimaryKey(CourseTestImages record);
    /**
     * 查询当前可用镜像
     */
    List<CourseTestImages> selectAllImagesName(@Param("imageName")String imageName,@Param("pageNum") Integer pageNum,@Param("pageSize") Integer pageSize);
    /**
     * 添加可用镜像
     */
    int insertCourseTestImages(CourseTestImages courseTestImages);
    /**
     * 根据镜像名批量删除可用镜像
     */
    int deleteCourseTestImages(String[] imagesNames);
    /**
     * 查询镜像总条数
     */
    int queryImageCount(String imageName);
}