package com.xgksyjxpt.xgksyjxpt.course.mapper.course;

import com.xgksyjxpt.xgksyjxpt.course.domain.course.CourseSectionImage;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CourseSectionImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section_image_t
     *
     * @mbggenerated Sat Dec 17 20:08:49 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section_image_t
     *
     * @mbggenerated Sat Dec 17 20:08:49 CST 2022
     */
    int insert(CourseSectionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section_image_t
     *
     * @mbggenerated Sat Dec 17 20:08:49 CST 2022
     */
    int insertSelective(CourseSectionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section_image_t
     *
     * @mbggenerated Sat Dec 17 20:08:49 CST 2022
     */
    CourseSectionImage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section_image_t
     *
     * @mbggenerated Sat Dec 17 20:08:49 CST 2022
     */
    int updateByPrimaryKeySelective(CourseSectionImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section_image_t
     *
     * @mbggenerated Sat Dec 17 20:08:49 CST 2022
     */
    int updateByPrimaryKey(CourseSectionImage record);
    /**
     * 上传章节图片
     */
    int uploadchapterImage(CourseSectionImage courseSectionImage);

    /**
     * 根据课程号删除已经上传的图片
     */
    int deleteImageByCid(String cid);
    /**
     * 根据课程号查询已经上传的图片url
     */
    List<String> selectImageUrlByCid(String cid);
    /**
     * 根据课程号与章节号删除已经上传的图片
     */
    int deleteImageByCidAndChapterId(@Param("cid") String cid,@Param("chapterId") Integer chapterId);

    /**
     * 根据课程号、章节号、小节号删除已经上传的图片
     */
    int deleteImageByCidAndChapterIdAndSectionId(@Param("cid") String cid,@Param("chapterId") Integer chapterId,@Param("sectionId") Integer sectionId);
    /**
     * 根据课程号与章节号查询已经上传的图片
     */
    List<String> selectImageUrlByCidAndChapterId(@Param("cid") String cid,@Param("chapterId") Integer chapterId);
    /**
     * 根据课程号、章节号、小节号查询已经上传的图片url
     */
    List<String> selectImageUrlByCidAndChapterIdAndSectionId(@Param("cid") String cid,@Param("chapterId") Integer chapterId,@Param("sectionId") Integer sectionId);
}